import { StyleSheet } from '@react-pdf/renderer'

export const s = StyleSheet.create({
  page: { padding: 34, fontSize: 11, color: '#111' },
  row: { flexDirection: 'row' },
  col: { flexGrow: 1 },
  h1: { fontSize: 32, fontWeight: 700, marginBottom: 4 },
  h2: { fontSize: 13, fontWeight: 700, marginTop: 7, marginBottom: 4 },
  h2Tight: { fontSize: 13, fontWeight: 700, marginTop: 0, marginBottom: 4 },
  label: { color: '#555' },
  box: { borderWidth: 1, borderStyle: 'solid', borderColor: '#e6e6e6', borderRadius: 6, padding: 8 },
  table: { borderWidth: 1, borderStyle: 'solid', borderColor: '#e6e6e6', borderRadius: 6, marginTop: 2 },
  tr: { flexDirection: 'row', borderBottomWidth: 1, borderStyle: 'solid', borderColor: '#e0e0e0' },
  th: { flex: 1, fontWeight: 700, fontSize: 11, padding: 8, backgroundColor: '#f7f7f7' },
  td: { flex: 1, padding: 8, fontSize: 11 },
  right: { textAlign: 'right' as const },
  small: { fontSize: 10, color: '#555' },
  logo: { width: 140, height: 55, objectFit: 'contain', marginBottom: 0, marginTop: -20 },
  companyDetails: { fontSize: 9, color: '#555', lineHeight: 1.4 },
  sep: { height: 8 },
  footerNote: { marginTop: 14, fontSize: 9, color: '#555' },
  block: { marginTop: 6 },

  pastelGreen: { backgroundColor: '#e8f7ec' },
  strike: { textDecoration: 'line-through', color: '#777' },

  itemCard: {
    backgroundColor: '#f5f6f8',
    borderRadius: 8,
    padding: 14,
    marginBottom: 10,
    flexDirection: 'row',
  },
  itemPhotoWrap: {
    width: 210,
    height: 210,
    backgroundColor: 'transparent',
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 6,
    position: 'relative',
    marginRight: 14,
    marginLeft: -8,
  },
  dimW: {
    position: 'absolute',
    bottom: -18,
    left: 0,
    right: 0,
    textAlign: 'center',
    fontSize: 10,
    color: '#333',
    paddingVertical: 3,
  },
  dimHWrap: {
    position: 'absolute',
    top: 0,
    bottom: -18,
    left: -6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dimH: {
    fontSize: 10,
    color: '#333',
    transform: 'rotate(-90deg)',
    paddingVertical: 3,
    paddingHorizontal: 3,
  },
  photo: {
    width: 170,
    height: 170,
    objectFit: 'contain',
  },

  itemContent: {
    flex: 1,
    paddingLeft: 14,
  },
  itemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  itemKind: {
    fontSize: 13,
    fontWeight: 700,
    color: '#111',
  },
  itemDims: {
    fontSize: 9,
    color: '#666',
    marginLeft: 6,
  },
  itemQty: {
    fontSize: 11,
    color: '#555',
    fontWeight: 500,
  },
  itemDescription: {
    fontSize: 9,
    color: '#666',
    marginBottom: 4,
  },
  itemRef: {
    fontSize: 9,
    color: '#666',
    marginTop: 2,
    marginBottom: 6,
  },
  hr: {
    height: 1,
    backgroundColor: '#e0e0e0',
    marginVertical: 12,
  },
  detailGrid: {},
  detailRow: {
    flexDirection: 'row',
    marginBottom: 2,
    marginTop: 6,
  },
  detailLabel: {
    width: '45%',
    color: '#555',
    paddingRight: 5,
    fontSize: 11,
  },
  detailValue: {
    flex: 1,
    fontWeight: 500,
    color: '#111',
    fontSize: 11,
  },
  piecesNote: {
    color: '#777',
    fontSize: 10,
  },
  headerGrid: { flexDirection: 'row', marginTop: 2 },
  colThird: { flex: 1, paddingLeft: 6, paddingRight: 6 },

  card: { borderWidth: 1, borderStyle: 'solid', borderColor: '#e6e6e6', borderRadius: 8, padding: 10, backgroundColor: '#ffffff' },
  brandCard: { backgroundColor: 'transparent', padding: 0 },
  clientCard: { backgroundColor: '#fdfdfd', borderWidth: 1, borderStyle: 'solid', borderColor: '#efefef', borderRadius: 8, padding: 10 },
  stampCard: { backgroundColor: '#fbfbfb', borderWidth: 1, borderStyle: 'dashed', borderColor: '#d1d5db', borderRadius: 10, padding: 10 },
  stampTitle: { fontSize: 11, fontWeight: 700, marginBottom: 2, color: '#111' },

  overline: { fontSize: 8, color: '#6b7280', marginBottom: 2 },
  metaRow: { fontSize: 10, color: '#0b0b0b', marginTop: 2 },
  metaLabel: { fontSize: 8, color: '#6b7280', marginRight: 4 },

  poBlock: { marginTop: 12, marginBottom: 0 },
  poInlineRow: { flexDirection: 'row', alignItems: 'center' },
  poImageSmall: { width: 60, height: 60, objectFit: 'contain', borderRadius: 6, alignSelf: 'flex-start', marginRight: 10 },
  poGrid: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 6 },
  poCol: { width: '50%', paddingRight: 8, paddingLeft: 2, paddingVertical: 4 },
  poFirstCol: { position: 'relative', paddingRight: 112 },
  poEyebrow: { color: '#6b7280', fontSize: 11, fontWeight: 400, marginBottom: 2 },
  poTitle: { fontSize: 16, fontWeight: 600, color: '#0b0b0b', marginBottom: 2 },
  poDesc: { color: '#6b7280', fontSize: 11, fontWeight: 400, lineHeight: 1.25, maxWidth: '220px' },
  poDivider: { width: 80, height: 2, backgroundColor: '#3fb26b', marginTop: 6, marginBottom: 6, alignSelf: 'flex-start' },
  poTitleRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 2 },
  poImageTiny: { width: 60, height: 60, objectFit: 'contain', borderRadius: 6, marginLeft: 6 },
  poTitleText: { lineHeight: 1.05, marginRight: 6 },
  poTitleRowTight: { flexDirection: 'row', alignItems: 'flex-end', marginBottom: 2 },
  poImageInline: { width: 50, height: 50, objectFit: 'contain', borderRadius: 4, marginLeft: 6, marginBottom: 1 },
  poHeroAbsWrap: { position: 'absolute', top: 0, bottom: 0, right: 8, width: 96, justifyContent: 'center', alignItems: 'flex-end' },
  poHeroAbs: { width: 96, height: 96, objectFit: 'contain', borderRadius: 4 },

  termsHeaderCard: { backgroundColor: '#f7f8fb', borderRadius: 16, padding: 18, marginTop: 8, marginBottom: 14 },
  termsProfileBadge: { fontSize: 8, color: '#6b7280', letterSpacing: 1.6, marginBottom: 6, textTransform: 'uppercase' as const },
  termsTagline: { fontSize: 19, fontWeight: 700, color: '#111827', marginBottom: 6 },
  termsSummary: { fontSize: 11, color: '#4b5563', lineHeight: 1.55 },
  termsValidityChip: { alignSelf: 'flex-start', backgroundColor: '#eef1f6', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 999, marginTop: 12 },
  termsValidityText: { color: '#374151', fontSize: 9.5, fontWeight: 600 },
  termsPaymentSection: { marginTop: 6, marginBottom: 16 },
  termsPaymentHeader: { fontSize: 9, color: '#6b7280', letterSpacing: 1.4, textTransform: 'uppercase' as const, marginBottom: 8 },
  termsPaymentGroupLabel: { fontSize: 9, color: '#9aa4b2', letterSpacing: 1.2, textTransform: 'uppercase' as const, marginBottom: 6, marginTop: 10 },
  termsPaymentRow: { flexDirection: 'row', gap: 14 },
  termsPlanCard: { flex: 1, borderRadius: 16, padding: 16, borderWidth: 1, borderStyle: 'solid', borderColor: '#e8ecf2', backgroundColor: '#fff' },
  termsPlanHeaderRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 6 },
  termsPlanTitleInline: { fontSize: 12, fontWeight: 700, color: '#111827' },
  termsPlanStep: { marginBottom: 12 },
  termsPlanStepRow: { flexDirection: 'row', alignItems: 'flex-start' },
  termsPlanStepCircle: { width: 22, height: 22, borderRadius: 11, backgroundColor: '#d1d5db', alignItems: 'center', justifyContent: 'center', marginRight: 8 },
  termsPlanStepCircleText: { fontSize: 9, fontWeight: 700, color: '#374151' },
  termsPlanStepLabel: { fontSize: 11.5, fontWeight: 600, color: '#1f2937' },
  termsPlanStepDesc: { fontSize: 10, color: '#6b7280', marginTop: 2, lineHeight: 1.45 },
  termsNotesIntro: { fontSize: 11, color: '#111827', lineHeight: 1.4, marginBottom: 6 },
  termsNotesList: { marginTop: 4 },
  termsNoteRow: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 6 },
  termsNoteBullet: { width: 6, height: 6, borderRadius: 3, backgroundColor: '#9aa4b2', marginTop: 5, marginRight: 8 },
  termsNoteText: { fontSize: 10, color: '#4b5563', lineHeight: 1.45, flex: 1 },
  termsSharedCard: { borderWidth: 1, borderStyle: 'solid', borderColor: '#edf0f5', borderRadius: 16, padding: 16, backgroundColor: '#f9fafc', marginBottom: 12 },
  termsSharedTitle: { fontSize: 9, fontWeight: 700, color: '#4b5563', textTransform: 'uppercase' as const, letterSpacing: 1.2, marginBottom: 8 },
  termsSharedGrid: { flexDirection: 'row', gap: 12 },
  termsSharedCol: { flex: 1 },
  termsSectionBlock: { borderWidth: 1, borderStyle: 'solid', borderColor: '#e5e7eb', borderRadius: 12, padding: 14, marginBottom: 10 },
  termsSectionTitle: { fontSize: 12, fontWeight: 700, color: '#0f172a', marginBottom: 6 },
  termsParagraph: { fontSize: 10, lineHeight: 1.5, color: '#6b7280', marginBottom: 6 },
  termsPrivacyCard: { backgroundColor: '#f5f6f8', borderRadius: 14, padding: 16, marginTop: 8, borderWidth: 1, borderStyle: 'solid', borderColor: '#e5e7eb' },
  termsPrivacyTitle: { color: '#111827', fontSize: 12, fontWeight: 700, marginBottom: 6 },
  termsPrivacyParagraph: { color: '#374151', fontSize: 10, lineHeight: 1.5, marginBottom: 4 },
  termsSupplyCard: { borderRadius: 16, padding: 18, backgroundColor: '#fff', borderWidth: 1, borderStyle: 'solid', borderColor: '#e8ecf2', marginBottom: 12 },
  termsSupplyEyebrow: { fontSize: 8.5, color: '#9aa4b2', letterSpacing: 1.6, textTransform: 'uppercase' as const },
  termsSupplyTitle: { fontSize: 16, fontWeight: 700, color: '#111827', marginTop: 4 },
  termsSupplySummary: { fontSize: 10, color: '#6b7280', marginTop: 4, marginBottom: 10, lineHeight: 1.45 },
  termsSupplySteps: { flexDirection: 'row', gap: 10 },
  termsSupplyStepCol: { flex: 1, borderRadius: 12, padding: 12, backgroundColor: '#f8fafc', borderWidth: 1, borderStyle: 'solid', borderColor: '#eef1f6' },
  termsIconWrap: { width: 20, height: 20, borderRadius: 10, backgroundColor: '#e5e7eb', alignItems: 'center', justifyContent: 'center', marginRight: 6 },
})
